name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Change file Permissions
      run: |
          sudo chmod -R 777 /home/ubuntu/actions-runner/_work/Bank/Bank/Bank
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file Bank/pom.xml
    - name: Run Spring tests
      run: mvn clean test --file Bank/pom.xml
    - name: App to JarFile
      run: |
          cd /home/ubuntu/actions-runner/_work/Bank/Bank/Bank
          sudo mvn clean package
    - name: Execute Jar File
      run: |
          cd /home/ubuntu/actions-runner/_work/Bank/Bank/Bank
          sudo nohup java -jar /home/ubuntu/actions-runner/_work/Bank/Bank/Bank/target/Bank-0.0.1-SNAPSHOT.jar > output.log &
